### ISSUE TITLE
Can't get @nx-extend/strapi to run correctly

### ISSUE THREAD

**Issue by jonesjaycob** [TriPSs/nx-extend#107]
When installing strapi with ```nx generate @nx-extend/strapi:init``` my project has errors with installing dependencies. 

From terminal 

```
Error while installing dependencies:

 Keep trying!             

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:
```

**Comment by TriPSs** [comment]
What are you using? Yarn/npm? 

With yarn you can use yarn workspaces as Strapi requires the dependencies to be inside the package.json of the project.

**Comment by TriPSs** [comment]
> What are you using? Yarn/npm?
> 
> With yarn you can use yarn workspaces as Strapi requires the dependencies to be inside the package.json of the project.

@hadnet same question for you :)

**Comment by TriPSs** [comment]
But did you try it with [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/)?

**Comment by TriPSs** [comment]
You probably do not need it but it's just something I have and know that that way everything is working correctly, Strapi requires to have the packages defined in the package.json where it lives so the normal install can give issues.
