### ISSUE TITLE
strapi build error

### ISSUE THREAD

**Issue by ngaritagoitia** [TriPSs/nx-extend#111]
running a fresh nx project with angular + strapi

after running nx g @nx-extend/strapi:init

it errors out, but if i cd into the strapi app and run npm it finishes the install.

however, trying to build the app yields this error:

![image](https://user-images.githubusercontent.com/122600877/223766366-2196ae90-632f-4e60-ad73-82128ee8e58b.png)

this doesn't happen with the build for the angular app.

using node 18.15.0 LTS

**Comment by caenderl** [comment]
Which TypeScript version are you using? Try to update to 4.9.x if you're on an older version.

**Comment by ngaritagoitia** [comment]
Hi! I'm using typescript 4.9.5

The way I managed to solve this was downgrading the following dependencies

![image](https://user-images.githubusercontent.com/122600877/226291266-f82acc6a-da52-4613-a15b-858250730c8f.png)

**Comment by TriPSs** [comment]
Going to close this as I see that the latest status is that it's solved?
