### ISSUE TITLE
--dry-run flag is not supported

### ISSUE THREAD

**Issue by gperdomor** [TriPSs/nx-extend#115]
**Actual behavior:**
Now when you try to generate the app using NX Console extension, the console execute the command with the --dry-run flag, but the app is created anyways

**Expected behavior:**
The app should not be created...

**Comment by TriPSs** [comment]
Could you elaborate a bit more? What package are you talking about for example.

**Comment by gperdomor** [comment]
@TriPSs sorry was for strapi package

**Comment by TriPSs** [comment]
Dry run is indeed not supported for the strapi package, if you want/needed you are free to create a PR.
