### ISSUE TITLE
[@nx-extend/strapi] Ready for nx 16?

### ISSUE THREAD

**Issue by Lp-Francois** [TriPSs/nx-extend#124]
When migrating to NX 16, I still have references for @nrwl/devkit blocking the upgrade in the yarn.lock

Using `yarn nx report`, I've inspected several community plugins installed on our monorepo, and found that `nx-extend/strapi` is installing a previous version of devkit: @nrwl/devkit.

`yarn why @nrwl/devkit`

```
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@nrwl/devkit"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...

=> Found "@nrwl/devkit@15.9.2"
info Has been hoisted to "@nrwl/devkit"
info Reasons this module exists
   - Hoisted from "@nx-extend#strapi#@nrwl#devkit"
   - Hoisted from "@nx-extend#strapi#@nrwl#workspace#@nrwl#devkit"
info Disk size without dependencies: "1.01MB"
info Disk size with unique dependencies: "1.66MB"
info Disk size with transitive dependencies: "3.72MB"
info Number of shared dependencies: 26

=> Found "@nx/devkit#@nrwl/devkit@16.3.2"
info This module exists because "@nx#devkit" depends on it.
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "972KB"
info Disk size with transitive dependencies: "4.67MB"
info Number of shared dependencies: 28

=> Found "@nx-extend/core#@nrwl/devkit@15.8.9"
info This module exists because "@nx-extend#strapi#@nx-extend#core" depends on it.
✨  Done in 0.89s.
```

I've seen the upgrade to 16 is in-progress in the PRs, any news about it?

➡️ https://github.com/TriPSs/nx-extend/pull/120#issuecomment-1535902156

I cannot see any references to alpha or beta in npm/github releases:
- https://www.npmjs.com/package/@nx-extend/strapi?activeTab=versions
- https://github.com/TriPSs/nx-extend/releases

I could even help to test the strapi package with latest version of nx :)

**Comment by Lp-Francois** [comment]
Thanks for the quick response :)

**Comment by TriPSs** [comment]
Latest version should now work correctly with NX 16.

**Comment by Lp-Francois** [comment]
Thanks so much! Gonna retry the nx upgrade of our monorepo :D
