### ISSUE TITLE
[readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

### ISSUE THREAD

**Issue by pvorona** [TriPSs/nx-extend#126]
This issue appears when executing build command.

Might need to add some checking [here](https://github.com/TriPSs/nx-extend/blob/master/packages/gcp-functions/src/utils/generate-package-json.ts#LL19C62-L19C84)?

<img width="747" alt="Screenshot 2023-06-22 at 18 15 20" src="https://github.com/TriPSs/nx-extend/assets/11915087/15402d7a-7b1d-4bc3-8134-0b2e3d049cb8">

**Comment by pvorona** [comment]
Correct, I'm on 16.3.2

**Comment by TriPSs** [comment]
Latest version should now work correctly with NX 16.
