### ISSUE TITLE
Nx v16, Cannot find module '@nrwl/cypress/src/executors/cypress/cypress.impl'

### ISSUE THREAD

**Issue by tarashrynevych** [TriPSs/nx-extend#129]
When using this package with "@nx/cypress": "16.3.2" I am getting this error:
`Error: Cannot find module '@nrwl/cypress/src/executors/cypress/cypress.impl'
Require stack:
- /PATH_TO_PROJECT/node_modules/@nx-extend/e2e-runner/src/executors/run/run.impl.js
- /PATH_TO_PROJECT/node_modules/nx/src/config/workspaces.js
- /PATH_TO_PROJECT/node_modules/nx/src/command-line/run/run.js
- /PATH_TO_PROJECT/node_modules/nx/bin/run-executor.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at /PATH_TO_PROJECT/node_modules/@nx-extend/e2e-runner/src/executors/run/run.impl.js:23:41
    at Generator.next (<anonymous>)
    at fulfilled (/PATH_TO_PROJECT/node_modules/@nx-extend/e2e-runner/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/PATH_TO_PROJECT/node_modules/@nx-extend/e2e-runner/src/executors/run/run.impl.js',
    '/PATH_TO_PROJECT/node_modules/nx/src/config/workspaces.js',
    '/PATH_TO_PROJECT/node_modules/nx/src/command-line/run/run.js',
    '/PATH_TO_PROJECT/node_modules/nx/bin/run-executor.js'
  ]
}
`

I noticed that when we use 'cypress' as a runner the logic inside packages/e2e-runner/src/executors/run/run.impl.ts, tries to import it from `@nrwl/cypress` which has been renamed to [@nx/cypress](https://www.npmjs.com/package/@nx/cypress). So changing 
`const cypressExecutor = require('@nrwl/cypress/src/executors/cypress/cypress.impl').default` 
to
`const cypressExecutor = require('@nx/cypress/src/executors/cypress/cypress.impl').default`
should resolve the issue.

Please let me know if you need more information or details.

**Comment by TriPSs** [comment]
This will be fixed with #128
