### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by ffMathy** [TriPSs/nx-extend#145]
Getting this:

```
└─┬ @nx-extend/pulumi 3.1.3
  └─┬ @nx-extend/core 4.3.0
    └── ✕ unmet peer tslib@2.5.3: found 2.6.1
```

I wonder what other libraries are doing with this kind of error to avoid getting out of date.

**Comment by TriPSs** [comment]
I think they add it to their peer dependencies all the versions they support.

**Comment by TriPSs** [comment]
Updating it here #146 :)
