### ISSUE TITLE
Getting routes undefined error in @nx-extend/strapi

### ISSUE THREAD

**Issue by nitintejuja** [TriPSs/nx-extend#153]
I'm getting below error in nx-extend/strapi latest version and im using nx latest version 
![image](https://github.com/TriPSs/nx-extend/assets/95347924/968dbae2-6aab-4f2c-94ae-24c68da8f158)
can anybody please help me here ?

**Comment by nitintejuja** [comment]
yes package using 4.12.1 version and im also using same version

**Comment by TriPSs** [comment]
Please update to the latest version as that one is using `4.13.x`

**Comment by nitintejuja** [comment]
@TriPSs this was the strapi build issue since mine project was completely js project which got resolved by adding below entry in tsconfig.json of strapi project 
```
 "allowJs": true //enables the build without .ts files
```

**Comment by TriPSs** [comment]
Thanks, reopened this ticket so we can add that.
