### ISSUE TITLE
GCP Functions issue: Unknown package manager: [object Object]?

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [TriPSs/nx-extend#160]
Hey I found your awesome plugins through the nx plugin directory.
I've played around a bit and have bben able to generate a cloud function.
When I try to build it I get below error.
Seems to be in the NX code itself. Weird is that if I add a log in the NX code the object is indeed the npm packageManager object.
Any ideas? Should I ask this in the NX repo instead?

-------------------------------------------------------------------------------------------------

PS C:\lander\devprojects\test-nx> nx build testit --region us-central1 --verbose

> nx run testit:build --region us-central1

asset main.js 773 bytes [compared for emit] (name: main) 1 related asset

webpack 5.88.2 compiled successfully (bcb26f377fbb6c20)

 >  NX   Unknown package manager: [object Object]

Error: Unknown package manager: [object Object]
    at getLockFileName (C:\lander\devprojects\test-nx\node_modules\nx\src\plugins\js\lock-file\lock-file.js:115:11)
    at createLockFile (C:\lander\devprojects\test-nx\node_modules\nx\src\plugins\js\lock-file\lock-file.js:128:44)
    at generatePackageJson (C:\lander\devprojects\test-nx\node_modules\@nx-extend\gcp-functions\src\utils\generate-package-json.js:68:149)
    at C:\lander\devprojects\test-nx\node_modules\@nx-extend\gcp-functions\src\executors\build\build.impl.js:12:61
    at Generator.next (<anonymous>)
    at fulfilled (C:\lander\devprojects\test-nx\node_modules\@nx-extend\gcp-functions\node_modules\tslib\tslib.js:112:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target build for project testit failed

   Failed tasks:

   - testit:build

---------------------------------------------------------------------------------------------------------------

<img width="976" alt="image" src="https://github.com/TriPSs/nx-extend/assets/1098243/ca14da49-73de-4d29-8020-2f2a865a5787">

**Comment by TriPSs** [comment]
Could you share `nx report` output?

**Comment by LanderBeeuwsaert** [comment]
@TriPSs so I've tried this again after reinstalling the plugin package (because I removed it in the meantime).
And now....... it works! :)
closing this
