### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by ffMathy** [TriPSs/nx-extend#166]
After updating to the latest version, I am getting the following error:

> Cannot find module '@angular-devkit/core'

Not sure why, because I am only using `@nx-extend/pulumi`. Any idea of why this may have started happening?

**Comment by ffMathy** [comment]
Hmmm yes, perhaps. I do have dependabot enabled, so I am constantly up to date. But this package was the only thing that got bumped it seems.

**Comment by TriPSs** [comment]
Could you run `nx report`?

**Comment by TriPSs** [comment]
Funny, If i run refresh I get the same. The code is also the same as preview which does work 🤔
