### ISSUE TITLE
Terraform Destroy Command

### ISSUE THREAD

**Issue by dansreis** [TriPSs/nx-extend#180]
I noticed that there doesn't seem to be a Terraform destroy command available in the Terraform executors. I wanted to inquire whether this is by design or if there are plans to include a destroy command in future updates.

Thank you for your time and effort in maintaining the nx-extend plugin. I appreciate the work!

**Comment by TriPSs** [comment]
No specific reason, we can add it.

**Comment by dansreis** [comment]
@TriPSs 
Will take care of that then. Thanks!

**Comment by TriPSs** [comment]
Thanks for the PR!
