### ISSUE TITLE
Pulumi: Support for setting working directory

### ISSUE THREAD

**Issue by ffMathy** [TriPSs/nx-extend#188]
In Pulumi, it's not possible right now to reference code from libraries etc. At least it seems to not build it properly.

What I propose would be a way to set the working directory for the Pulumi executors.

That way, I can disable TypeScript for my project, and have esbuild build it first before running up, and then run it towards the dist folder.

Where do I start with this, if I am to contribute with a PR?

**Comment by TriPSs** [comment]
I do not undertand it completely? You want to disable typescript and compile the code? What is the benefit of that?

**Comment by ffMathy** [comment]
Yes, and follow this:
https://www.pulumi.com/docs/languages-sdks/javascript/#disabling-built-in-typescript-support

The reason right now is that when I try to import something from a library I made, it fails. Maybe due to some ESM/CommonJS issue with that library.

And I guess that's because Pulumi will try to run the project directly (maybe via ts-node)? But NX in general builds using esbuild.

So I thought that by disabling TypeScript in the project and running Pulumi from the dist folder (and setting the "up" target to depend on the "build" target), it would ensure the same type of building/compilation is being used.

All of this could be accomplished by just one setting that allows adjustment of the working directory.

Maybe we could get inspired by https://nx.dev/nx-api/js/executors/node (the Node executor)? In there, you can either specify a depending configuration (to make it infer output directory of the build step and set that was the working directory), or you can specify a "main" file directly.

That allows for the best of both.

I hope this makes some sense.

**Comment by TriPSs** [comment]
Intresting, just a quick question: you do have a `tsconfig.json` in the root of you pulumi app that looks like this:
```json
{
  "extends": "../../../tsconfig.base.json"
}
```

Together with this at the top of your index.ts
```ts
import { loadConfig, register } from 'tsconfig-paths'

const config = loadConfig(__dirname)
if (config.resultType === 'failed') {
  console.log('Could not load tsconfig to map paths, aborting.')
  process.exit(1)
}

register({
  baseUrl: config.absoluteBaseUrl,
  paths: config.paths
})
```

Cause that should make it work to use nx libs inside your Pulumi app.

We could also look at compiling it all ourself and then run Pulumi inside the dist folder (by indeed defining a `buildTarget` option) but gotta say that for everything I use Pulumi for it will be a big overkill sinde with the code shared above you can also use your libs (at-least in my case :) ).

**Comment by ffMathy** [comment]
Yeah, I have that code (see below). The problem is actually not importing the library itself. That part works. The problem then arises when my library imports something from the AWS SDK. And that then fails (but only when run via Pulumi).

I agree with your assessment - fixing the root problem (if possible) would be better, but if the option is simple to implement (accepting both solutions and a default that doesn't require anything different than today), would you be interested in accepting such a PR?

Here's an example of my error
```
Previewing update (sandbox):
     Type                 Name         Plan     Info
     pulumi:pulumi:Stack  iac-sandbox           1 error

Diagnostics:
  pulumi:pulumi:Stack (iac-sandbox):
    error: Running program '/workspaces/src/apps/common-iac/' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    ../../libs/@common/src/infrastructure/parameter-store.ts: error TS2339: Property 'send' does not exist on type 'SSMClient'.
```

So my project (`common-iac`) is importing something from `parameter-store.ts` in my own library ( `@common`). That file in that library is then importing something from the AWS SDK, and that import fails via Pulumi, but not when running via NX (or the tests for that matter).

## `common-iac/index.ts` (my Pulumi project)
```typescript
/* eslint-disable no-console */
import { loadConfig, register } from 'tsconfig-paths';

const config = loadConfig('.');
if (config.resultType === 'failed') {
  console.log('Could not load tsconfig to map paths, aborting.');
  process.exit(1);
}

register({
  baseUrl: config.absoluteBaseUrl,
  paths: config.paths,
});

import './pulumi';

export * from './pulumi';
```

## `common-iac/pulumi.ts` (also in my Pulumi project)
```typescript
import { createFtrackSession } from '@common/infrastructure/parameter-store';
```

## `@common/infrastructure/parameter-store.ts` (my library project)
```typescript
import { GetParameterCommand, ParameterNotFound, SSMClient } from '@aws-sdk/client-ssm';

export async function getParameterStoreValue(path: string) {
  const ssm = new SSMClient({
    region: 'eu-west-1',
  });
  try {
    const result = await ssm.send( //this is the line that fails compilation
      new GetParameterCommand({
        Name: path,
        WithDecryption: true,
      }),
    );

    return result.Parameter?.Value;
  } catch (e) {
    if (e instanceof ParameterNotFound) {
      throw new Error(`Parameter store value not found for path: ${path}`);
    }

    throw e;
  }
}
```

So that way, I know that the imports themselves are working. But not when they then import a particular library (other libraries seem to work fine).

I hope that clarifies a bit.

**Comment by ffMathy** [comment]
That's great! Any idea of where to start? How do I add options?

Also, do you have an idea of why this might be happening? Because if we fix the root cause, then (as you say) there's no need for the path workaround.

I suspect maybe the SSM package from AWS is ESM, and my projects are CommonJS. But not sure.

**Comment by TriPSs** [comment]
You try to make something like the builder for google cloud functions, see [here](https://github.com/TriPSs/nx-extend/blob/master/packages/gcp-functions/src/executors/build/build.impl.ts#L23), this one also calls an existing Nx executor to compile to code.

You could give that a try by actually defining that inside your own build target, run it, than try to run Pulumi command yourself inside the dist.  If it's working than we can add the compiler executor to the generators of the Pulumi package and run Pulumi inside the dist folder (also probably creating that yaml file to disable typescript automatically).

Hope it's a bit clear, if you want you can also join a [slack team](https://join.slack.com/t/nestjsquery/shared_invite/zt-27dvu0tye-tOcAmeQ0PRSCEInW6P3h9g) that I have for an other open source project, than we can also discuss it there.
