### ISSUE TITLE
@nx-extend/e2e-runner doesn't kill devServerTarget on SIGINT

### ISSUE THREAD

**Issue by milo526** [TriPSs/nx-extend#202]
I use the `@nx-extend/e2e-runner` with the `cypress` runner and the following config

```json
{
  "executor": "@nx-extend/e2e-runner:run",
  "options": {
    "runner": "cypress",
    "cypressConfig": "apps/web-app-e2e/cypress.config.ts",
    "devServerTarget": "web-app:serve:testing",
    "testingType": "e2e",
    "headless": false,
    "watch": true,
    "targets": [
      {
        "target": "socket-api:serve:testing",
        "checkUrl": "https://socket.rc.local:3002/health-check",
        "checkMaxTries": 300,
        "reuseExistingServer": true,
        "rejectUnauthorized": false
      },
      {
        "target": "api:serve:testing",
        "checkUrl": "https://api.rc.local:3001/health-check",
        "checkMaxTries": 300,
        "reuseExistingServer": true,
        "rejectUnauthorized": false
      }
    ]
  },
}
```

The tests run perfectly fine with this setup; but killing cypress using `ctrl+c`, fails to kill the `web-app:serve:testing` properly.
It gives the following output 

> Stopping target "socket-api:serve:testing"
> Stopping target "api:serve:testing"
> The Test Runner unexpectedly exited via a exit event with signal SIGINT
> 
> Please search Cypress documentation for possible solutions:
> 
> https://on.cypress.io
> 
> Check if there is a GitHub issue describing this crash:
> 
> https://github.com/cypress-io/cypress/issues
> 
> Consider opening a new issue.
> 
> ----------
> 
> Platform: darwin-arm64 (23.1.0)
> Cypress Version: 13.5.1

The fact that the `web-app:serve:testing` task stays active keeps the port occupied and therefor prevents the tests from being re-started (as well as using up resources).

**Comment by TriPSs** [comment]
I think this is because `"devServerTarget": "web-app:serve:testing",` is handled by Cypress and not this lib, try removing `devServerTarget` and add it to `targets`.

**Comment by milo526** [comment]
That was indeed my initial solution; but that seems to remove all logging output; and the watch functionality?

**Comment by TriPSs** [comment]
Watch and everything keeps working, try doing `--verbose` and you will get all the logging of the targets.

**Comment by milo526** [comment]
Thanks for the quick response; that does indeed seem to be the case.

Using `--verbose` adds a lot of logging, how would you feel about a PR that makes the logging configurable?
It seems like that should be easily manageable by updating the [nx-target class](https://github.com/TriPSs/nx-extend/blob/master/packages/e2e-runner/src/executors/run/utils/nx-target.ts#L178).

My proposal would be to add a `logging` option to the target. Where `logging: true` would enable logging, and `logging: false` would use the current configuration.
We could also use `logging: true` to enable logging, `logging: false` to always disable logging for that target, and `logging: undefined` for the current setup?

**Comment by TriPSs** [comment]
Yes that is a great idea!
