### ISSUE TITLE
Question: How does the `deploy` Executor deal with `node_modules` with GCP functions

### ISSUE THREAD

**Issue by tolgap** [TriPSs/nx-extend#220]
Given I have an Nx monorepo with _hundres_ of dependencies in `package.json`
And given I have a Cloud Function `apps/my-cf`
When `apps/my-cf/package.json` only contains 3 dependencies

How does the `deploy` executor ensure that I only deploy the GCP function with those 3 packages (and their transitive deps) in `node_modules`?

**Comment by TriPSs** [comment]
After the code is compiled it checks the output for 'require' and checks that against the root package.json, if the package exists there it's added to the functions package.json

**Comment by tolgap** [comment]
I see! So GCP performs the installation of the packages!

I've been building them wrong the whole time, performing an `npm install` before building and deploying. So that `npm install` step is unnecessary as its done by GCP! Thanks @TriPSs !
