### ISSUE TITLE
terraform module: How to specify working directory?

### ISSUE THREAD

**Issue by mflores-lovingly** [TriPSs/nx-extend#253]
In my nx setup, I've got all terraform resources in sourceRoot/src and I'd like nx-extend/terraform to run commands from that directory. I've been trying to get the --directory flag to work but haven't been able to figure it out. Appending "/src" to the source root works but isn't helpful as I have other commands in the project that need to operate from the current source root.

Is specifying a working directory supported in the terraform module? Can someone provide an example of what project.json would look like with a specified working directory?

**Comment by TriPSs** [comment]
The terraform module uses `sourceRoot` from the `project.json`, there are no other options.
