### ISSUE TITLE
nx add <ui lib> button conflicts with regular nx add

### ISSUE THREAD

**Issue by Evanion** [TriPSs/nx-extend#254]
The `add` executor in `@nx-extend/shadcn-ui` conflicts with `nx` built in `nx add`
When I try to run `nx add ui button`, nx thinks that I want to add a lib called `ui` from the public npm registry rather than calling the `add` executor and add a shadcn component to my ui lib.

versions:
nx 18.3.2
@nx-extend/shadcn-ui 1.0.2

`nx show project ui`:
```
{
  "root": "libs/ui",
  "targets": {
    "add": {
      "executor": "@nx-extend/shadcn-ui:add",
      "options": {},
      "configurations": {}
    }
  },
  "name": "ui",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "libs/ui/src",
  "projectType": "library",
  "tags": [],
  "implicitDependencies": []
}

```

**Comment by Evanion** [comment]
well what you are really doing is downloading code to your repo, but `download` seems wrong somehow.
But I suppose just prefixing it a bit would suffice, so perhaps `shadd` as a contracted `shadcn add` would work.

**Comment by Evanion** [comment]
> I am just using `add-component` in my project (my `project.json` follows):
> 
> ```json
> {
>   "name": "ui-components",
>   "$schema": "../../node_modules/nx/schemas/project-schema.json",
>   "sourceRoot": "libs/ui-components/src",
>   "projectType": "library",
>   "tags": [],
>   "targets": {
>     "add-component": {
>       "executor": "@nx-extend/shadcn-ui:add"
>     }
>   }
> }
> ```

Thats a good workaround. But I think the default keyword should be a functional one, as most users won't try to rename their commands.

**Comment by TriPSs** [comment]
Agree with @Evanion, will make a patch that also has a migration.

**Comment by flickz** [comment]
I followed @gurisko `add-component` but I can't seems to get the executable running

```
> nx run ui:add-component button


Running:  yarn shadcn-ui@latest add button --path=src --cwd=ui
yarn run v1.22.21
error Command "shadcn-ui@latest" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target add-component for project ui (650ms)

      With additional flags:
        button

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

``` 

I'm using yarn, but I was expecting`npx  shadcn-ui@latest add button --path=src --cwd=ui`
