### ISSUE TITLE
Wrong commands for react-email serve and export executors

### ISSUE THREAD

**Issue by Lper258** [TriPSs/nx-extend#277]
react-email command has wrong command defined

### Export (_node_modules/@nx-extend/react-email/src/executors/export/export.impl.ts_)

**Current**

```
return execPackageManagerCommand(buildCommand([
    'react-email export', // This line is the problem
    `--dir=${sourceRoot || root}`,
    `--outDir=${options.outputPath}`,
    options.pretty && `--pretty`,
    options.plainText && `--plainText`
  ]), {
    env: process.env
  })
```

**Supposed to be**

```
return execPackageManagerCommand(buildCommand([
    'email export',  // This fixes the problem
    `--dir=${sourceRoot || root}`,
    `--outDir=${options.outputPath}`,
    options.pretty && `--pretty`,
    options.plainText && `--plainText`
  ]), {
    env: process.env
  })
```

### Serve (_node_modules/@nx-extend/react-email/src/executors/serve/serve.impl.ts_)

**Current**

```
return execPackageManagerCommand(buildCommand([
    'react-email dev',
    `--dir=${sourceRoot || root}`,
    options.port && `--port=${options.port}`
  ]), {
    env: process.env
  })
```

**Supposed to be**

```
return execPackageManagerCommand(buildCommand([
    'email dev',
    `--dir=${sourceRoot || root}`,
    options.port && `--port=${options.port}`
  ]), {
    env: process.env
  })
```

I can make a PR for this, just let me know if the issue is correctly reported and not a problem with my config.

**Comment by TriPSs** [comment]
What package manager are you using? I recently changed this because Yarn was unable to install the package `email`. 

Changed it to `react-email` as that is the actual package name, it should then check the bin of that package.

**Comment by Lper258** [comment]
I am using Yarn.

I'm not really sure that I had the same problem, as the only thing I did was I manually changed the commands in transpiled `*.impl.js` files from `react-email [command]` to `email [command]` and then everything seemed to work.

**Comment by TriPSs** [comment]
What version of yarn? Could you share some logs to?

**Comment by Lper258** [comment]
Yarn: 1.22.19
OS: Mac OS Sonoma, Version 14.4.1 (Apple Silicon)

### Log 1
```

> nx run emails:serve


Running:
yarn react-email dev --dir=apps/emails/src
error Command "react-email" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Log 2

```
 NX   Running target serve for project emails failed

Failed tasks:

- emails:serve

Hint: run the command with --verbose for more details.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 *  The terminal process "/bin/zsh '-l', '-c', 'yarn nx run emails:serve'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by TriPSs** [comment]
Maybe update to the latest version of yarn (4)? Then it will use 'yarn dlx' which is the same as npx.

Otherwise you could set a environment variable that will force nx-extend to use npx.
