### ISSUE TITLE
--verbose also makes Pulumi more verbose

### ISSUE THREAD

**Issue by ffMathy** [TriPSs/nx-extend#279]
Right now, passing `--verbose` to the NX commandline with the Pulumi executors, also causes the Pulumi output to be more verbose.

This is not desirable. `--verbose` in NX is often used just to make NX also show output from dependent projects/targets when building a particular target.

So for instance, because I am running "up" on Project A and Project A depends on Project B, I also want to see the "up" output of Project B. For that, `--verbose` is used in NX.

But here, it also makes Pulumi spam way more. Where in the code is this happening? Then I can make a contribution. My suggestion is to rename the Pulumi input parameter.

**Comment by TriPSs** [comment]
I think this is because `--debug` does the same as `--verbose`, which causes `USE_VERBOSE_LOGGING_MINIMAL` to be true and therefore `--debug` to be passed to Pulumi.

I'm not sure yet how we can improve this as I would like to keep the `--verbose`/`USE_VERBOSE_LOGGING_MINIMAL` implementation.

**Comment by ffMathy** [comment]
Could we turn it around? Maybe have a default that isn't noisy, and you can opt-in to the noisiness?

Or perhaps add so we can at least opt out? Perhaps with another environment variable?

**Comment by TriPSs** [comment]
> Could we turn it around? Maybe have a default that isn't noisy, and you can opt-in to the noisiness?

This is currently the case ofc, if you don't provide the `--verbose` Pulumi will not run in debug mode.

Regarding your use-case, what I tend to do when I want to see the full output of all affect I run with `--output-style=stream` ([This is also how nx-extend actions run it](https://github.com/TriPSs/nx-extend/blob/51acd5ec26c66415d482da05829a1cc4d6fbd81f/actions/run-many/src/utils/run-target.ts#L36))

**Comment by ffMathy** [comment]
That works! Thanks. Didn't know about that flag!
