### ISSUE TITLE
Error: No "outputPath" option found!

### ISSUE THREAD

**Issue by creaux** [TriPSs/nx-extend#291]
Hello,

following issue seems on place of webpack wiring with nx is not working properly.

```
Error: No "outputPath" option found!
    at withNx (/Users/creaux/Development/inbdm/packages/strapi/src/with-nx.ts:41:13)
    at module.exports (/Users/creaux/Development/inbdm/apps/strapi/src/admin/webpack.config.js:7:10)
    at Object.mergeConfigWithUserConfig (/Users/creaux/Development/inbdm/node_modules/@strapi/admin/_internal/node/webpack/config.ts:209:14)
    at <anonymous> (/Users/creaux/Development/inbdm/node_modules/@strapi/admin/_internal/node/webpack/build.ts:11:25)
```

While web pack file after generation:

```
'use strict';

const { withNx } = require('@nx-extend/strapi');

module.exports = (config, webpack) => {
  return withNx(config, webpack);
};

```

Where `config` param output is as following. No outputPath present.

```
{
  ...
  output: {
    path: '/Users/creaux/Development/inbdm/apps/strapi/dist/build',
    publicPath: '/admin/',
    filename: '[name].[contenthash:8].js',
    chunkFilename: '[name].[contenthash:8].chunk.js'
  },
  ...
}
```

```
❯ nx report

 NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : darwin-arm64
bun    : 1.1.13

nx (global)        : 19.1.1
nx                 : 19.3.1
@nx/js             : 19.3.1
@nx/jest           : 19.3.1
@nx/linter         : 19.3.1
@nx/eslint         : 19.3.1
@nx/workspace      : 19.3.1
@nx/devkit         : 19.3.1
@nx/esbuild        : 19.3.1
@nx/eslint-plugin  : 19.3.1
@nx/node           : 19.3.1
@nrwl/tao          : 19.3.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@nx-extend/strapi                   : 10.0.3

```

**Comment by TriPSs** [comment]
Could you share your project.json? Does it have a `outputPath` configured in the options of the build target?

**Comment by creaux** [comment]
Interesting it does.

```
{
  "name": "strapi",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  "sourceRoot": "apps/strapi/src",
  "targets": {
    "serve": {
      "executor": "@nx-extend/strapi:serve",
      "options": {}
    },
    "build": {
      "executor": "@nx-extend/strapi:build",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/strapi",
        "tsConfig": "apps/strapi/tsConfig.json"
      },
      "configurations": {
        "production": {
          "production": true
        }
      }
    }
  },
  "tags": []
}
```

**Comment by TriPSs** [comment]
You are trying to build or serve it? Do you have the issue with both?

**Comment by TriPSs** [comment]
Could you create a repo that has this issue? I have also checkt my local installations but cannot reproduce the issue, the latest PR containing changes for Strapi also passed the build in the E2E tests.

**Comment by creaux** [comment]
The situation is following. Running Strapi first time so don't know yet difference especially between serving commands. By common sense I have started with `develop`.

- Target `build` is well aligned with config and works. No `outputPath` issue.
- `develop` has problem with `outputPath`
- `serve` works
- `start` only works after `serve` is executed and interrupted

However I guess apart from develop those other issues are maybe just due to not yet understanding how are they designed in relation to nx package implementation.

I see that serve coming from `project.json`. While develop is solely related to Strapi itself despite of integrated by this package. 

```

```

**Comment by TriPSs** [comment]
Aaah, so if I understand you correct you are using the commands from the package.json? That probably causes the issues.

You can run the following commands:
- `nx build <strapi-project>` to build
- `nx serve <strapi-project>` to run "develop" mode, I also tend to add `--watchAdmin`.

**Comment by creaux** [comment]
Sorry for confusion, I'm using `nx`. Was just pointing out on observation this is what detects nx under the hood.

![Screenshot 2024-06-21 at 23 33 28](https://github.com/TriPSs/nx-extend/assets/1745028/094616f2-0b11-473b-9a52-f10269753cff)

Clearly seems to depend on `serve` may be way to go.

**Comment by TriPSs** [comment]
Good one, nx indeed copies over the package json scripts, not very handy for the strapi package.

Think its a good idea that after we unit the project we remove all the ones we do not support.

**Comment by ChristianLoosliVGT** [comment]
i tried to deploy strapi with nx deploy strapi, and now i get the following error in the cloud console:

Error: Cannot find module '@nx-extend/strapi'
 Require stack:
 - /opt/app/src/admin/webpack.config.js
 - /opt/app/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js
 - /opt/app/node_modules/@strapi/admin/dist/cli.js
 - /opt/app/node_modules/@strapi/admin/index.js
 - /opt/app/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js
 - /opt/app/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js
 - /opt/app/node_modules/@strapi/strapi/dist/commands/index.js
 - /opt/app/node_modules/@strapi/strapi/dist/cli.js
 - /opt/app/node_modules/@strapi/strapi/bin/strapi.js
     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
     at Module._resolveFilename (/opt/app/node_modules/esbuild-register/dist/node.js:4799:36)
     at Module._load (node:internal/modules/cjs/loader:1051:27)
     at Module.require (node:internal/modules/cjs/loader:1311:19)
     at require (node:internal/modules/helpers:179:18)
     at Object.<anonymous> (/opt/app/src/admin/webpack.config.js:3:20)
     at Module._compile (node:internal/modules/cjs/loader:1469:14)
     at Module._compile (/opt/app/node_modules/esbuild-register/dist/node.js:2258:26)
     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
     at newLoader (/opt/app/node_modules/esbuild-register/dist/node.js:2262:9) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/opt/app/src/admin/webpack.config.js',
     '/opt/app/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js',
     '/opt/app/node_modules/@strapi/admin/dist/cli.js',
     '/opt/app/node_modules/@strapi/admin/index.js',
     '/opt/app/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js',
     '/opt/app/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js',
     '/opt/app/node_modules/@strapi/strapi/dist/commands/index.js',
     '/opt/app/node_modules/@strapi/strapi/dist/cli.js',
     '/opt/app/node_modules/@strapi/strapi/bin/strapi.js'
   ]
 }

what am i doing wrong?

**Comment by ChristianLoosliVGT** [comment]
i tried to deploy strapi with nx deploy strapi, and now i get the following error in the cloud console:

Error: Cannot find module '@nx-extend/strapi'
 Require stack:
 - /opt/app/src/admin/webpack.config.js
 - /opt/app/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js
 - /opt/app/node_modules/@strapi/admin/dist/cli.js
 - /opt/app/node_modules/@strapi/admin/index.js
 - /opt/app/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js
 - /opt/app/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js
 - /opt/app/node_modules/@strapi/strapi/dist/commands/index.js
 - /opt/app/node_modules/@strapi/strapi/dist/cli.js
 - /opt/app/node_modules/@strapi/strapi/bin/strapi.js
     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
     at Module._resolveFilename (/opt/app/node_modules/esbuild-register/dist/node.js:4799:36)
     at Module._load (node:internal/modules/cjs/loader:1051:27)
     at Module.require (node:internal/modules/cjs/loader:1311:19)
     at require (node:internal/modules/helpers:179:18)
     at Object.<anonymous> (/opt/app/src/admin/webpack.config.js:3:20)
     at Module._compile (node:internal/modules/cjs/loader:1469:14)
     at Module._compile (/opt/app/node_modules/esbuild-register/dist/node.js:2258:26)
     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
     at newLoader (/opt/app/node_modules/esbuild-register/dist/node.js:2262:9) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/opt/app/src/admin/webpack.config.js',
     '/opt/app/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js',
     '/opt/app/node_modules/@strapi/admin/dist/cli.js',
     '/opt/app/node_modules/@strapi/admin/index.js',
     '/opt/app/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js',
     '/opt/app/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js',
     '/opt/app/node_modules/@strapi/strapi/dist/commands/index.js',
     '/opt/app/node_modules/@strapi/strapi/dist/cli.js',
     '/opt/app/node_modules/@strapi/strapi/bin/strapi.js'
   ]
 }

what am i doing wrong?

**Comment by TriPSs** [comment]
> Think its a good idea that after we init the project we remove all the ones we do not support.

The scripts from the package.json are not supported.

**Comment by ChristianLoosliVGT** [comment]
> > Good one, nx indeed copies over the package json scripts, not very handy for the strapi package.
> > Think its a good idea that after we init the project we remove all the ones we do not support.
> 
> The scripts from the package.json are not supported.

hmmm...how can you then deploy?

**Comment by ChristianLoosliVGT** [comment]
is it a better solution to have strapi within the repository but not to use it with nx? then you can also use the latest version of strapi.

**Comment by TriPSs** [comment]
Depends on your use case, our use cases do not deploy Strapi to the Strapi cloud (Think that is what the deploy does?), instead we build our own docker files and deploy that.

**Comment by ChristianLoosliVGT** [comment]
yeah my usecase is to deploy to strapi cloud. so what would you do in my case? is it a good idea to have strapi outside nx but in the same repo?

**Comment by TriPSs** [comment]
Build the project and make sure the output is where Strapi cloud expects it to be and add `@nx-extend/strapi` to the package.json of the Strapi project. 

Further I would not know since we do not use Strapi cloud.
