### ISSUE TITLE
ERROR: No cached ProjectGraph is available with gcp-task-runner and NX >v19.3

### ISSUE THREAD

**Issue by NickDub** [TriPSs/nx-extend#294]
Using the “@nx-extend/gcp-task-runner” plugin, for all NX versions >v19.3, I get this error: 

<img width="598" alt="image" src="https://github.com/user-attachments/assets/d03e1593-8f65-412a-bf1c-303a9e63bef2">

**Comment by TriPSs** [comment]
What version of the package are you using? Could you run `nx report`.

**Comment by NickDub** [comment]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/9f489c52-f761-4800-a504-a1ba321a3703">

**Comment by TriPSs** [comment]
Interesting, we did have some of these issues but that was mainly with < Nx 19.3, I will update everything soon again so will check it out.

**Comment by NickDub** [comment]
Yes, it is in the package.json

<img width="242" alt="image" src="https://github.com/user-attachments/assets/945ebd3a-7ea5-42c8-bf33-5e79f8c38336">

**Comment by TriPSs** [comment]
Could you update that one? The latest version is `10.0.4`

**Comment by NickDub** [comment]
OK, I'll wait for the update then.
Thanks

**Comment by TriPSs** [comment]
Packages have been updated, can you give it a try?

**Comment by NickDub** [comment]
It works now.
Thanks
