### ISSUE TITLE
Outdated @nx-extend/terraform causes issues with yarn 4

### ISSUE THREAD

**Issue by mhp-borisbojic** [TriPSs/nx-extend#299]
There are two issues with the current version of @nx-extend/terraform

1. When doing an `nx report`, it wells me that e.g. `@nrwl/workspace` should match my installed version of NX, which is odd: I don't have specified `@nrwl/workspace` in my package.json According to the NX docs, `@nrwl/workspace` was renamed to `@nx/workspace` anyway (see also https://github.com/nrwl/nx/issues/27398)
2. @nrwl/workspace forced outdated versions of nx@npm to be resolved using yarn 4, which results in a failing CI/CD pipeline. Removing your packet removes this issue (see also https://github.com/nrwl/nx/issues/27397)

Is there any update planned on @nx-extend/terraform to match the latest available NX version?

**Comment by TriPSs** [comment]
Interesting as `@nx-extend/terraform` does not use `@nx/workspace`.

**Comment by mhp-borisbojic** [comment]
> Interesting as `@nx-extend/terraform` does not use `@nx/workspace`.

But it requests nx@npm which then asks for the other packages:

```
  - @nrwl/workspace@19.3.0
  - @nrwl/devkit@19.3.0
  - @nrwl/tao@19.3.0
 ```

**Comment by TriPSs** [comment]
Okay, created PR to update Nx to the latest version and adding them as to `peerDependencies` so it should no longer conflict.
