### ISSUE TITLE
No way to turn off verbose logging

### ISSUE THREAD

**Issue by ffMathy** [TriPSs/nx-extend#312]
Since relatively recently, the Pulumi commands have started being super verbose on my CI environment.

And there's no way to turn it off.

I think this needs a code change.

**Comment by TriPSs** [comment]
I'm not a-where of changes that could do that

**Comment by ffMathy** [comment]
Maybe you are right.

If you look in: https://github.com/TriPSs/nx-extend/blob/master/packages/core/src/utils/use-verbose-logging.ts

Pulumi is verbose if `USE_VERBOSE_LOGGING_MINIMAL` is truthy.

But I don't have those environment variables set in my code. Maybe #313 can fix it? Not sure.

**Comment by TriPSs** [comment]
Those variables are set by nx when you run with '--verbose'

**Comment by ffMathy** [comment]
That's the weird part. I'm not using that either.

**Comment by TriPSs** [comment]
Did you by any change updated nx? Maybe they are now always setting they in the ci?

**Comment by TriPSs** [comment]
That variable is always overwritten by Nx, I will check what comes out of it these days and possibly update the check.

**Comment by ffMathy** [comment]
Thank you.

**Comment by TriPSs** [comment]
Nx indeed changed the way they set the variable, it used to be either `true` or `undefined`, looks like it's now `true` or `false`. 

I will update the check.

**Comment by ffMathy** [comment]
Awesome! Thanks!
