### ISSUE TITLE
Error running a new project using @nx-extend/strapi & pnpm

### ISSUE THREAD

**Issue by gjsoaresc** [TriPSs/nx-extend#315]
I'm trying to add strapi to my NX monorepo but when  I run serve this error appears.
Using latest version in a brand new NX monorepo.
Happens only using pnpm dlx

<img width="631" alt="image" src="https://github.com/user-attachments/assets/39510a77-a3fa-4300-bbfc-3937e1af88fa">

**Comment by aufdenpunkt** [comment]
Hi @gjsoaresc, I'm currently facing the same issue. Did you solve it?

Thanks and best,
Chris

**Comment by gjsoaresc** [comment]
> Hi @gjsoaresc, I'm currently facing the same issue. Did you solve it?
> 
> 
> 
> Thanks and best,
> 
> Chris

Heyy, i solved by creating a patch removing the ignore prompts as it is deprecated. If you want to use version 5 i suggest you to change to turborepo e.e

**Comment by TriPSs** [comment]
Think that the main issue with this is that it does not install the latest version (Yarn has the same issue), forcing the command to use `npx` will also fix that.
