### ISSUE TITLE
"FOREIGN KEY constraint failed" error NX >v19.7.0

### ISSUE THREAD

**Issue by NickDub** [TriPSs/nx-extend#316]
Hello, since NX v19.7.0, I have this error that block my CI: 

<img width="296" alt="image" src="https://github.com/user-attachments/assets/b8577c2c-617a-4376-9113-499ba0caa5fd">

I think it's linked to this new feature: https://github.com/nrwl/nx/pull/26891

**Comment by NickDub** [comment]
On this project, I use “@nx-extend/gcp-task-runner@v8.0.1", while on others, where I don't use it, I don't have the problem.

**Comment by TriPSs** [comment]
I cannot reproduce this issue locally, please provide steps.

**Comment by NickDub** [comment]
Sorry, but we only have the problem on our CI environment. 😞 
Maybe it has something to do with the fact that the peerDependency of "@nx-extend/gcp-task-runner" is: 
```
  "peerDependencies": {
    "@nx/devkit": "^19.6.0"
  }
```

Could you update to version >19.7.0?

**Comment by TriPSs** [comment]
Since it's prefixed with `^` 19.7 is also a accepted version, could you check your lockfile of older versions of Nx? And check what is installing them, also run `nx report`

**Comment by NickDub** [comment]
I found that"@nx-extend/gcp-task-runner" use "@nx/workspace": "19.6.1" 😉 

<img width="306" alt="image" src="https://github.com/user-attachments/assets/79266ac6-7a61-4ea4-b266-e284d4407ea9">

**Comment by TriPSs** [comment]
Let me move that one also to the peer deps.

**Comment by NickDub** [comment]
Hi @TriPSs ,
NX 19.8.0 has been released. Do you have a date for your new version?

**Comment by NickDub** [comment]
Hi @TriPSs ,
The v8.0.2 solves the problem. Thank's a lot 😉
