### ISSUE TITLE
How to upgrade to Strapi v4?

### ISSUE THREAD

**Issue by minusculepengu** [TriPSs/nx-extend#32]

**Comment by TriPSs** [comment]
Think we need to update `strapi-generate-new` for that.

**Comment by hellojere** [comment]
I tried figuring this out, but wasn't that straightforward - very new to extending NX. Anyhow, this would be highly appreciated.

**Comment by BorisZubchenko** [comment]
As I can see, `strapi-generate-new` [is deprecated](https://github.com/strapi/strapi-generate-new). Consider using `@strapi/generate-new`, it has similar if not the same API.
