### ISSUE TITLE
Documentation confusing. 

### ISSUE THREAD

**Issue by bbarclay** [TriPSs/nx-extend#334]
WORKS:  ---->.  nx add @nx-extend/shadcn-ui libs/shaddycat button

that's what I used. 

My Ui was named shaddycat

and utils was named

nx add @nx-extend/shadcn-ui libs/shaddycatutils button. ---- Don't use this one.

**Comment by bbarclay** [comment]
Never mind that doesn't work either.

**Comment by TriPSs** [comment]
`add` was renamed to `add-component` as it now conflicted with a target from Nx, there was a migration for this. Looks like we forgot to update the README.

**Comment by bbarclay** [comment]
yarn shadcn-ui@0.8.0 add button --path=src --cwd=shadcnUi
yarn run v1.22.22
warning ../../package.json: No license field
error Command "shadcn-ui@0.8.0" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

—————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target add-component for project shadcnUi (1s)

      With additional flags:
        button

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

View structured, searchable error logs at https://nx.app/runs/CsLWofAptB
