### ISSUE TITLE
Support Gen 2 GCP functions with higher memory

### ISSUE THREAD

**Issue by whygee-dev** [TriPSs/nx-extend#338]
Currently the maximum memory for GCP functions is 4096MB while GCP functions do support 8192MB and 16Gb / 32Gb if it is a gen 2

**Comment by whygee-dev** [comment]
Are you open to a pull request ?

**Comment by TriPSs** [comment]
Pr is welcome!

**Comment by whygee-dev** [comment]
https://github.com/TriPSs/nx-extend/pull/339
