### ISSUE TITLE
Outdated shadcn-ui plugin

### ISSUE THREAD

**Issue by bzp2010** [TriPSs/nx-extend#340]
## Description

Some time ago, the shadcn-ui project added a new sidebar component and I tried to add it in the ui project and I got the following error, it looks like the component does not exist.

```
nx add-component shadcn-ui sidebar

> nx run shadcn-ui:add-component sidebar


Running:
pnpm dlx shadcn-ui@0.8.0 add sidebar --path=src --cwd=packages/shadcn-ui
Selected components not found. Exiting.
```

I checked the docs for shadcn-ui and they mention that the project has switched to the new command line `shadcn` instead of the `shadcn-ui@0.8.0` that we're still using, and I'm guessing that maybe it's causing the problem I'm having.

I tried switching to shadcn's direct use on the new command line, and it also had some issues such as not being able to find the `package.json` or asking me to recreate the project among some other things.

Do you have any ideas about this?  **Thanks 🙏**

**Comment by TriPSs** [comment]
Please see #309 for some more info.

**Comment by bzp2010** [comment]
Hi @TriPSs

I have created a PR but I am not familiar with that repository, could you please check? 🫡
