### ISSUE TITLE
Node 16 support

### ISSUE THREAD

**Issue by fbcarpinato** [TriPSs/nx-extend#38]
If I try to create a new strapi application with node 16 I get the following error

> error strapi@0.1.0: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "16.13.0"

The project gets created but the nx.json is not updated and project.json is missing from the app

**Comment by TriPSs** [comment]
I think we should start with #32 and update strapi package, that will probably solve this to.
