### ISSUE TITLE
Missing command `generate` and arguments

### ISSUE THREAD

**Issue by stefanbinder** [TriPSs/nx-extend#50]
Hey,

a few commands are still missing in the extension.
One important for me is:
`strapi generate`

and also that arguments are passed onto the next command, eg.:
`nx r strapi-app:serve --watch-admin` is just executing `npx strapi develop` instead of `npx strapi develop --watch-admin`

Some more commands:
`strapi admin:create-user`
`strapi templates:generate`
`strapi routes:list`

all the commands are listed here: https://docs.strapi.io/developer-docs/latest/developer-resources/cli/CLI.html

**Comment by TriPSs** [comment]
Hi,

Could you create a PR for those?

**Comment by stefanbinder** [comment]
I'll gladly have a look 🙂

**Comment by JohnnyDevNull** [comment]
I would also be interested in a more complete integration.
Did you already started something @stefanbinder ?

**Comment by stefanbinder** [comment]
Hey @JohnnyDevNull 
I was working on it, but so far I just was able to improve the `serve` command.  
Integrating the interactive `generate` command is not working that easily - no input is going through.

You can try to solve it, what I did was writing a very small node-script what would start the process.

First I tried with the already in use shelljs:
```
const shelljs = require('shelljs');
shelljs.exec('npx strapi generate');
```
Just the output is displayed, but no further stdin is going through (I tried many options).

Then I tried directly with node's child_process:
```
let cp = require('child_process');
let child = cp.spawn('npx', ['strapi', 'generate']);

child.stdout.on('data', function (data) {
  console.log('stdout: ' + data);
});

child.stdin.end();
```

Maybe you find a good way to move all the input through to the `generate` child-process.

**Comment by TriPSs** [comment]
@stefanbinder (late reply I know 😅), shelljs does not support that, see how the Pulumi plugin does it, that one passes down input.
