### ISSUE TITLE
Add Node16 to GCP Functions

### ISSUE THREAD

**Issue by Brian-McBride** [TriPSs/nx-extend#51]
The current enum is listed only up to `node14`

https://github.com/TriPSs/nx-extend/blob/17f49f4173228681b0a833ea47a3351638fc86c9/packages/gcp-functions/src/executors/deploy/schema.json#L33

**Comment by prmichaelsen** [comment]
oh is that why my runs weren't working

**Comment by Brian-McBride** [comment]
Looking at the code, the `runtime` is not required. If you don't provide it, it defaults to `nodejs16`
I didn't realize that as I like to explicitly set important values like that. 

It probably doesn't make a huge difference, but Functions v2 is in beta now and this plugin still uses the Alpha commands. But maybe it will break something?

**Comment by TriPSs** [comment]
Not quite sure if it matters that it's still using `alpha`, would have to test it to be sure as in some cases not all functionality (like setting db connection or secrets) was not yet available in `beta`.

Would you mind creating a PR for the enum?
