### ISSUE TITLE
Build folder under dist/apps/strapi is missing some stuff

### ISSUE THREAD

**Issue by hasansamNol** [TriPSs/nx-extend#73]
When building using yarn nx run strapi:build it generates a dist folder with needed stuff to run the project. It runs just fine but there are missing stuff from the webpack build compared to the yarn nx run strapi:serve build. 

You can notice you wont have the internationalisation or any other plugins in settings panel if running the the dist/apps/strapi using yarn start or a custom server as when running the serve you will have all the functionalities in the admin panel

Any workarounds for this?

**Comment by TriPSs** [comment]
What version of `@nx-extend/strapi` are you using?
