### ISSUE TITLE
@nx-extend/e2e-runner - ignore ssl errors

### ISSUE THREAD

**Issue by milo526** [TriPSs/nx-extend#82]
We use the `@nx-extend/e2e-runner` package to start related application before we run our tests.
These applications however, do not have properly signed certificates since they are used in a test environment. They instead use self-signed certificates.

Would it be possible to add an option to ignore ssl error when checking if the related applications are started.

It seems like updating the axios instance [in `is-api-live-ts`](https://github.com/TriPSs/nx-extend/blob/master/packages/e2e-runner/src/executors/run/utils/is-api-live.ts#L4) with a custom https-agent would already solve this.

This should probably be configurable and an opt-in.

```ts
import axios from 'axios'
import https from 'https'

export const isApiLive = async (url: string): Promise<boolean> => {
  const agent = new https.Agent({
    rejectUnauthorized: false
  });

  return axios.get(url, {
    timeout: 500,
    httpsAgent: agent
  }).then((response) => {
    return response.status >= 200 && response.status < 300

  }).catch(() => {
    return false
  })
}
```

**Comment by TriPSs** [comment]
That's a good idea! Could you create a PR?
