### ISSUE TITLE
Add the GCP Cloud Functions Serve builder 

### ISSUE THREAD

**Issue by zackarydev** [TriPSs/nx-extend#84]
https://github.com/TriPSs/nx-extend/blob/cb84cae484a6a3bf9378903404525b5fd39a7c4d/packages/gcp-functions/executors.json#L24

Which should build something along the lines of:
```
"serve": {
      "executor": "nx:run-commands",
      "options": {
        "buildTarget": "$myproject:build",
        "commands": [
          {
            "command": "nodemon --watch ./dist/apis/$myproject --exec functions-framework --target=$FunctionName --source ./dist/apis/$myproject"
          }
        ]
      }
    },
```

**Comment by TriPSs** [comment]
You can generate a [runner](https://github.com/TriPSs/nx-extend/blob/master/packages/gcp-functions/src/generators/init-runner/init.impl.ts) that can run multiple / all your functions in your project.
