### ISSUE TITLE
@ng-extend/e2e-runner - Incorrectly reports existing server as not available.

### ISSUE THREAD

**Issue by milo526** [TriPSs/nx-extend#86]
Regardless of the actual state of the server, the e2e-runner will always report the state of the target as not-live at least once.

We can look at [the `waitFor` method in the `nx-target`class](https://github.com/TriPSs/nx-extend/blob/master/packages/e2e-runner/src/executors/run/utils/nx-target.ts#L109-L131)

https://github.com/TriPSs/nx-extend/blob/8502c9394e84f517a904f86c151a53ff9cc6b184/packages/e2e-runner/src/executors/run/utils/nx-target.ts#L109-L131

It will always set the `serverIsLive` variable to `false` at the first run of the while-loop, resulting in this log message.

Could we replace the line 114; the assignment of `serverIsLive` with `let serverIsLive = await waitFn();`

This should correctly set the initial state, giving a slight boost to start-up times and removing a somewhat confusing log message.

Furthermore it might be nice to add a log message to when we re-use an existing service.

https://github.com/TriPSs/nx-extend/blob/8502c9394e84f517a904f86c151a53ff9cc6b184/packages/e2e-runner/src/executors/run/utils/nx-target.ts#L59-L67

Would be happy to send in a MR if you agree with these point!

**Comment by TriPSs** [comment]
I completely agree, a PR would be awesome :D
