### ISSUE TITLE
Inject env variables into project.json  [@nx-extend/e2e-runner:run]

### ISSUE THREAD

**Issue by pkonieczniak** [TriPSs/nx-extend#88]
Hi! First of all, thanks for creating this plugin!

Do you know if there is possibility to inject `.env` variables into plugin config? 
Instead of having static values in "checkUrl", I'd like values from .env file. Especially in `checkUrl` field.
I checked `nx` docs but I didn't find info about this.

```json
{
  "root": "apps/my-front/",
  "targets": {
    "e2e": {
      "executor": "@nx-extend/e2e-runner:run",
      "options": {
        "runner": "cypress",
        "cypressConfig": "./cypress.config.ts",
        "devServerTarget": "my-front:serve",
        "testingType": "e2e",
        "targets": [
          {
            "target": "my-api:serve",
            "checkUrl": "http://localhost:3555", // Use a dynamic value different for local and CI based on .env
            "checkMaxTries": 50,
            "rejectUnauthorized": false
          }
        ]
      }
    }
  }
}
```

**Comment by TriPSs** [comment]
That's a good idea! We could do something like `"checkUrl": "$ENV_VARIABLE"`

**Comment by pkonieczniak** [comment]
Yes, it looks that this should work. 

When nx command is executed env variables are loaded automatically (in my case from .env).
We can check if the value starts with an alias for example as you suggested `$`  and override certain key in `this._options`.

Actually, I'm not sure if this is the best solution but it should work.

![image](https://user-images.githubusercontent.com/24206452/205678322-56cc4307-b664-4a8e-a56d-c26134ab199e.png)

**Comment by TriPSs** [comment]
Yea a PR would be awesome!
