### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by electroheadfx** [TriPSs/nx-extend#91]
Hey thanks for this repo, do you have a sample for run it because I don't understand how choose the app to deploy, what is the .firebase.json syntax for --site ? thanks in advance for your assistance :)-

**Comment by TriPSs** [comment]
I think you are talking about `@nx-extend/firebase-hosting`? You can add it to one of your apps by running `nx g @nx-extend/firebase-hosting:add`

Every project within firebase can hold multiple sites, the `--site` option is to define the site you want to deploy to in that firebase project.

**Comment by electroheadfx** [comment]
it was about gcd-cloud-run (it has a --site option, so on what you told me its for firebase hosting). To be honest I don't how run gcd-cloud-run extension on vs-code or bash CLI. Can you show me this ? thanks

**Comment by TriPSs** [comment]
Aah I see, the `--site` option described in the README of `gcp-cloud-run` should not be there.

**Comment by electroheadfx** [comment]
ah ok, but could you drive how run @nx-extend/gcp-cloud-run ?
```bash
pnpm nx list @nx-extend/gcp-cloud-run

 >  NX   Capabilities in @nx-extend/gcp-cloud-run:

   EXECUTORS/BUILDERS

   deploy : Deploy executor
```
how use the deploy command in bash ?

**Comment by TriPSs** [comment]
Not sure that I understand but the deploy command cannot be used in bash you should define it in your nx app's project json.

**Comment by electroheadfx** [comment]
but how should be used @nx-extend/gcp-cloud-run ?

**Comment by TriPSs** [comment]
Think you misunderstand these packages, all the packages in this repo work with [nx](https://nx.dev/), not on their own.

**Comment by electroheadfx** [comment]
Yes I use NX but I don't know how they work with it. Sorry for the confusion.

**Comment by TriPSs** [comment]
You can then add the following to your projects json file
```
"deploy": {
      "executor": "@nx-extend/gcp-cloud-run:deploy",
      "options": {
        "name": "main",
        "dockerFile": ".google/docker-files/Dockerfile.nestjs",
        "envVars": {
        }
      }
    }
```

Then you can run `nx deploy <your-app>`

**Comment by electroheadfx** [comment]
is there an option for change the path of google hosting, actually its setup on `gcr.io` but from my side its on `eu.gcr.io`
thanks !

**Comment by TriPSs** [comment]
`gcr.io` is for container registery right? Cloud run uses artifact registry these days, so if you deploy to eu west the container will go to the artifact registry in that region

**Comment by electroheadfx** [comment]
beautiful, thanks for your patience!
